//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teatr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelList
    {
        public int id { get; set; }
        public string hotelname { get; set; }
        public string @class { get; set; }
        public string term { get; set; }
        public string status { get; set; }
    }
}
